// Lista completa de raças de cachorro para o quiz
// Ordenada alfabeticamente, com opções especiais no início

export const DOG_BREEDS = [
  // Opções especiais primeiro
  "Raça mista",
  "Outra Raça",
  
  // Mais populares
  "Labrador Retriever",
  "Pastor-alemão",
  "Golden Retriever",
  "Pit Bull Terrier Americano",
  "Buldogue Francês",
  "Poodle",
  "Shih Tzu",
  "Yorkshire Terrier",
  "Border Collie",
  "Chihuahua",
  "Beagle",
  "Welsh Corgi Pembroke",
  "Husky Siberiano",
  
  // A-Z
  "Afador",
  "Afaird",
  "Affen Border Terrier",
  "Affen Spaniel",
  "Affen Tzu",
  "Affenchon",
  "Affengriffon",
  "Affenhuahua",
  "Affenpinscher",
  "Affenpoo",
  "Affenpug",
  "Affenshire",
  "Affenwich",
  "Afghan Bay Retriever",
  "Afghan Chon",
  "Afghan Collie",
  "Afghan Retriever",
  "Afghan Sheepdog",
  "Afghan Spaniel",
  "Afollie",
  "Africanis",
  "Aidi",
  "Airedale Shepherd",
  "Airedale Terrier",
  "Airedoodle",
  "Aki-Poo",
  "Akita Americano",
  "Akita Chow",
  "Akita Inu",
  "Akita Pit",
  "Alano",
  "Alano Espanhol",
  "Alaskan Klee Kai",
  "Alopekis",
  "American Staffordshire Terrier",
  "Anglo-francês da Pequena Vénerie",
  "Anglo-francês de Médio Porte",
  "Antigo Terrier Inglês",
  "Aussiedoodle",
  "Aussiepom",
  "Austrian Black And Tan Hound",
  "Azawakh",
  "Basenji",
  "Basset Alemão da Vestfália",
  "Basset Alpino",
  "Basset Artesiano Normando",
  "Basset Azul da Gasconha",
  "Basset Fulvo da Bretanha",
  "Basset Hound",
  "Beagle Harrier",
  "Bearded Collie",
  "Beauceron",
  "Bedlington Terrier",
  "Bernedoodle",
  "Bichon Bolonhês",
  "Bichon Frisé",
  "Billy",
  "Bluetick Coonhound",
  "Boerboel",
  "Boiadeiro Australiano",
  "Boiadeiro Australiano de Cauda Chata",
  "Boiadeiro Galego",
  "Boiadeiro da Flandres",
  "Boiadeiro das Ardenas",
  "Boiadeiro de Appenzell",
  "Boiadeiro de Berna",
  "Boiadeiro de Entlebuch",
  "Borador",
  "Border Terrier",
  "Borzoi",
  "Borzoi (Galgo Russo)",
  "Boston Terrier",
  "Boxer",
  "Boxerdoodle",
  "Boxspring",
  "Boykin Spaniel",
  "Braco Alemão",
  "Braco Alemão de Pelo Curto",
  "Braco Alemão de Pelo Duro",
  "Braco Alemão de Pelo Longo",
  "Braco Alemão de Pelo Áspero",
  "Braco Dinamarquês",
  "Braco Eslovaco",
  "Braco Eslovaco de Pelo Duro",
  "Braco Francês tipo Gascão",
  "Braco Francês tipo Pirineus",
  "Braco Griffon da Vendeia",
  "Braco Húngaro de Pelo Curto (Vizsla)",
  "Braco Húngaro de Pelo Duro",
  "Braco Italiano",
  "Braco Polonês",
  "Braco Tirolês",
  "Braco da Estíria de Pelo Duro",
  "Braco da Transilvânia",
  "Braco de Ariège",
  "Braco de Auvérnia",
  "Braco de Burbônia",
  "Braco de Saint-Germain",
  "Branco e Laranja Francês",
  "Branco e Preto Francês",
  "Brittany",
  "Broholmer",
  "Buhund Norueguês",
  "Buldogue",
  "Buldogue Alapaha de Sangue Azul",
  "Buldogue Americano",
  "Buldogue Australiano",
  "Buldogue Frenchton ",
  "Buldogue Miniatura",
  "Bull Terrier",
  "Bull Terrier Miniatura",
  "Bulmastife",
  "Ca de Bou",
  "Cairmal",
  "Cairn Terrier",
  "Cane Corso Italiano",
  "Cavachon",
  "Cavador",
  "Cavalier King Charles Spaniel",
  "Cavapoo",
  "Cesky Fousek",
  "Cesky Terrier",
  "Chabrador",
  "Chart Polski",
  "Cheagle",
  "Chesapeake Bay Retriever",
  "Chi-Poo",
  "Chien-gris",
  "Chilier",
  "Chin Tibetano",
  "Chinook",
  "Chipin",
  "Chippiparai",
  "Chisoxy de Pelo Duro",
  "Chiweenie",
  "Chizer",
  "Chorkie",
  "Chow Chow",
  "Chug",
  "Chusky",
  "Cierny Sery",
  "Cimarron Uruguaio",
  "Cimarrón Uruguayo",
  "Cirneco do Etna",
  "Clumber Spaniel",
  "Cockalier",
  "Cockapoo",
  "Cocker Spaniel Americano",
  "Cocker Spaniel Inglês",
  "Collie de Pelo Curto",
  "Collie de Pelo Longo",
  "Combai",
  "Coonhound Preto e Castanho",
  "Corgi Galês Cardigan",
  "Corgi Inu",
  "Corgidor",
  "Coton de Tulear",
  "Cotonese",
  "Cumberland Sheepdog",
  "Curly-coated Retriever",
  "Cursinu",
  "Cuvac Eslovaco",
  "Cão Chinês de Chongqing",
  "Cão Chiribaya",
  "Cão Esquimó Americano",
  "Cão Esquimó Canadense",
  "Cão Fazendeiro da Dinamarca e Suécia",
  "Cão Finlandês da Lapônia",
  "Cão Havaiano Poi",
  "Cão Imperial Chinês",
  "Cão Islandês de Pastoreio",
  "Cão Lebre Indiano",
  "Cão Leopardo da Catahoula",
  "Cão Lituano",
  "Cão Lutador da Córdoba",
  "Cão Pelado Peruano",
  "Cão Polar Argentino",
  "Cão Polinésio",
  "Cão d'Água Americano",
  "Cão d'Água Espanhol",
  "Cão d'Água Francês",
  "Cão d'Água Frisão",
  "Cão d'Água Português",
  "Cão d'Água Romagna",
  "Cão d'Água St. John",
  "Cão da Carolina",
  "Cão da Groenlândia",
  "Cão da Serra da Estrela",
  "Cão da Serra de Aires",
  "Cão de Aponte Frisão",
  "Cão de Artois",
  "Cão de Canaã",
  "Cão de Castro Laboreiro",
  "Cão de Caça da Polônia",
  "Cão de Crista Chinês",
  "Cão de Fila da Terceira",
  "Cão de Fila de São Miguel",
  "Cão de Gado Transmontano",
  "Cão de Guarda de Moscou",
  "Cão de Montanha dos Pirenéus",
  "Cão de Montanha dos Pirineus",
  "Cão de Pastor Belga",
  "Cão de Presa Canário",
  "Cão de Presa Maiorquino",
  "Cão de Santo Humberto",
  "Cão de Taiwan",
  "Cão de Ursos da Carélia",
  "Cão do Ariége",
  "Cão do Atlas (Aidi)",
  "Cão do Taiti",
  "Cão-cantor da Nova Guiné",
  "Cão-farejador de Hanôver",
  "Cão-lobo Checoslovaco",
  "Cão-lobo Tibetano",
  "Cão-lobo de Kunming",
  "Cão-lobo de Saarloos",
  "Dachsador",
  "Dachshund",
  "Dandie Dinmont Terrier",
  "Decker Hunting Terrier",
  "Deerhound",
  "Dingo",
  "Doberdor",
  "Doberman",
  "Dobermann Pinscher",
  "Docker",
  "Dogo Argentino",
  "Dogo Cubano",
  "Dogo Guatemalteco",
  "Dogue Alemão",
  "Dogue de Bordeaux",
  "Dorgi",
  "Dorkie",
  "Double Doodle",
  "Doxiepoo",
  "Doxle",
  "Drever",
  "Duck Tolling Retriever da Nova Escócia",
  "Dunker",
  "Dálmata",
  "Elkhound Norueguês Cinza",
  "Elkhound Norueguês Preto",
  "Elo",
  "Eurasier",
  "Eurohound",
  "Field Spaniel",
  "Fila Brasileiro",
  "Flat-coated Retriever",
  "Fo-Chon Miniatura",
  "Fo-Chon de Pelo Duro",
  "Fo-Tzu Miniatura",
  "Fo-Tzu de Pelo Duro",
  "Foodle Miniatura",
  "Foodle de Pelo Duro",
  "Fox Beagle Miniatura",
  "Fox Beagle de Pelo Duro",
  "Fox Pinscher Miniatura",
  "Fox Terrier Chileno",
  "Fox Terrier Escocês de Pelo Duro",
  "Fox Terrier Miniatura",
  "Fox Terrier de Pelo Duro",
  "Fox Terrier de Pelo Liso",
  "Foxhound Americano",
  "Foxhound Inglês",
  "Foxie Doxie Miniatura",
  "Foxie Doxie de Pelo Duro",
  "Foxillon Miniatura",
  "Foxingese Miniatura",
  "Foxingese de Pelo Duro",
  "Foxker Miniatura",
  "Foxker Miniatura de Pelo Duro",
  "Foxker de Pelo Duro",
  "Foxton Miniatura",
  "Foxton de Pelo Duro",
  "Foxy Rat Terrier Miniatura",
  "Foxy Rat Terrier de Pelo Duro",
  "Foxy Russell Miniatura",
  "Foxy Russell de Pelo Duro",
  "Foxybull Terrier Miniatura",
  "Foxybull Terrier de Pelo Duro",
  "Francais Blanc et Noir",
  "French Brittany",
  "Gaddi Kutta",
  "Galgo Afegão",
  "Galgo Caravan",
  "Galgo Espanhol",
  "Galgo Farejador de Creta",
  "Galgo Húngaro",
  "Galgo Inglês",
  "Galgo Italiano",
  "Galgo Polonês",
  "Galguinho Italiano",
  "Gampr Armênio",
  "Gascão Saintongeois",
  "Glen of Imaal Terrier",
  "Goberian",
  "Goldador",
  "Goldendoodle",
  "Goldenmute do Alasca",
  "Gollie",
  "Grand Fauve de Bretagne",
  "Grande Anglo-francês Branco e Laranja",
  "Grande Anglo-francês Branco e Preto",
  "Grande Anglo-francês Tricolor",
  "Grande Azul da Gasconha",
  "Grande Basset Griffon da Vendeia",
  "Grande Boiadeiro Suíço",
  "Grande Cão da Serra da Suíça",
  "Grande Griffon da Vendeia",
  "Grande Mastim de Borinque",
  "Grande Munsterlander",
  "Griffon Azul da Gasconha",
  "Griffon Belga",
  "Griffon Fulvo da Bretanha",
  "Griffon de Aponte de Pelo Duro",
  "Griffon de Aponte de Pelo Duro Korthals",
  "Griffon de Bruxelas",
  "Griffon de Caça Checo",
  "Griffon de Nivernais",
  "Harrier",
  "Havanese",
  "Hokkaido",
  "Horgi",
  "Hortaya Borzaya",
  "Hovawart",
  "Husky do Alasca",
  "Inuit do Norte",
  "Jack Chi",
  "Jack Russell Terrier",
  "Jafox de Pelo Duro",
  "Jagdterrier",
  "Jindo-coreano",
  "Jämthund",
  "Kai",
  "Kaikadi",
  "Kangal",
  "Kanni",
  "Keeshond",
  "Kelpie Australiano",
  "Kerry Beagle",
  "Kerry Blue Terrier",
  "King Charles Spaniel",
  "Kintamani",
  "Kintamani-bali Dog",
  "Kishu",
  "Kleiner Münsterländer",
  "Kokoni",
  "Komondor",
  "Kooikerhondje",
  "Koolie",
  "Kromfohrländer",
  "Kuchi Afegão",
  "Kuri",
  "Kuvasz",
  "Kyi-Leo",
  "Lab Pointer",
  "Labernese",
  "Labmaraner",
  "Labrabull",
  "Labradane",
  "Labradoodle",
  "Labrador Husky",
  "Labrastaff",
  "Labsky",
  "Lagotto Romagnolo",
  "Laika Russo Europeu",
  "Laika da Sibéria Ocidental",
  "Laika da Sibéria Oriental",
  "Laika da Yakutia",
  "Lakeland Terrier",
  "Lancashire Heeler",
  "Landseer (Europa Continental)",
  "Lapphund Sueco",
  "Lebréu Escocês",
  "Leonberger",
  "Lhasa Apso",
  "Lowchen",
  "Lucas Terrier",
  "Lulu da Pomerânia",
  "Lundehund Norueguês",
  "Lurcher",
  "Mahratta Greyhound",
  "Majestic Tree Hound",
  "Malador do Alasca",
  "Malamute do Alasca",
  "Maltipoo",
  "Maltês",
  "Manchester Terrier",
  "Manchester Terrier Miniatura",
  "Mastador",
  "Mastim",
  "Mastim Alpino",
  "Mastim Americano",
  "Mastim Espanhol",
  "Mastim Kumaon",
  "Mastim Napolitano",
  "Mastim Paquistanês",
  "Mastim Tibetano",
  "Mastim Ultimate",
  "Mastim dos Pirineus",
  "Mini Chisoxy",
  "Molosso de Épiro",
  "Morkie",
  "Mountain Feist",
  "Mucuchies",
  "Mudi",
  "Nederlandse Kooikerhondje",
  "New Zealand Heading Dog",
  "Norfolk Spaniel",
  "Norfolk Terrier",
  "Norrbottenspets",
  "North Country Beagle",
  "Norwich Terrier",
  "Old Croatian Sighthound",
  "Old English Sheepdog",
  "Old Welsh Grey Sheepdog",
  "Otterhound",
  "Pachón Navarro",
  "Paisley Terrier",
  "Pandikona",
  "Papillon",
  "Parson Russell Terrier",
  "Pastor Akita",
  "Pastor Branco Americano",
  "Pastor Garafiano",
  "Pastor Inglês",
  "Pastor Maremano Abruzês",
  "Pastor Miorítico",
  "Pastor Romeno Miorítico",
  "Pastor Romeno dos Cárpatos",
  "Pastor da Anatólia",
  "Pastor da Picardia",
  "Pastor da Rússia Meridional",
  "Pastor da Ásia Central",
  "Pastor de Beauce",
  "Pastor de Brie",
  "Pastor de Gales",
  "Pastor de Karst",
  "Pastor de Nova Zelândia",
  "Pastor de Shetland",
  "Pastor de Shiló",
  "Pastor de Tatra",
  "Pastor do Cáucaso",
  "Pastor do Leste Europeu",
  "Pastor do Sudeste Europeu",
  "Pastor dos Pirineus de Pelo Curto",
  "Pastor dos Pirineus do Pelo Curto",
  "Pastor-alemão de Pelo Comprido",
  "Pastor-americano Miniatura",
  "Pastor-australiano",
  "Pastor-australiano Miniatura",
  "Pastor-belga",
  "Pastor-belga Laekenois",
  "Pastor-belga Malinois",
  "Pastor-belga Tervuren",
  "Pastor-bergamasco",
  "Pastor-boêmio",
  "Pastor-branco Suíço",
  "Pastor-catalão",
  "Pastor-croata",
  "Pastor-da-picardia",
  "Pastor-de-tatra",
  "Pastor-finlandês da Lapônia",
  "Pastor-holandês",
  "Pastor-jugoslavo (Sharplanina)",
  "Pastor-maiorquino",
  "Pastor-polonês da Planície",
  "Pastor-rei",
  "Patterdale Terrier",
  "Peekapoo",
  "Pequeno Azul da Gasconha",
  "Pequeno Basset Griffon da Vendeia",
  "Pequeno Brabançon",
  "Pequeno Cão Leão",
  "Pequeno Cão Russo",
  "Pequeno Sabujo Suíço",
  "Pequinês",
  "Perdigueiro Alemão de Pelo Curto",
  "Perdigueiro Alemão de Pelo Duro",
  "Perdigueiro Português",
  "Perdigueiro de Burgos",
  "Petit Basset Griffon Vendéen",
  "Phalene",
  "Pharaoh Hound",
  "Phu Quoc Ridgeback",
  "Pinscher Alemão",
  "Pinscher Austríaco",
  "Pinscher Miniatura",
  "Pit Bull do Alasca",
  "Pitsky",
  "Plott Hound",
  "Plummer Terrier",
  "Pocket Beagle",
  "Podenco Andaluz",
  "Podengo Canário",
  "Podengo Ibicenco",
  "Podengo Português",
  "Podengo Português Pequeno",
  "Pointer Inglês",
  "Poitevin",
  "Pom Terrier Miniatura",
  "Pom Terrier de Pelo Duro",
  "Pomapoo",
  "Pomchi",
  "Pomeagle",
  "Pomsky",
  "Poochon",
  "Poodle Miniatura",
  "Poodle Toy",
  "Porcelana",
  "Poxer Miniatura",
  "Poxer de Pelo Duro",
  "Prague Ratter",
  "Prazsky Krysarik",
  "Presa Canário",
  "Pudelpointer",
  "Pug",
  "Pugabull Americano",
  "Puggle",
  "Puli",
  "Pumi",
  "Pungsan",
  "Rafeiro do Alentejo",
  "Rajapalayam",
  "Rampur Greyhound",
  "Rastreador Brasileiro",
  "Rat Doxie Miniatura",
  "Rat Terrier",
  "Ratonero Bodeguero Andaluz",
  "Ratonero Mallorquín",
  "Ratonero Murciano de Huerta",
  "Ratonero Valenciano",
  "Redbone Coonhound",
  "Rhodesian Ridgeback",
  "Rottweiler",
  "Rough Collie",
  "Russian Tsvetnaya Bolonka",
  "Sabueso Espanol",
  "Sabueso Fino Colombiano",
  "Sabujo Alemão",
  "Sabujo Eslovaco",
  "Sabujo Espanhol",
  "Sabujo Estoniano",
  "Sabujo Finlandês",
  "Sabujo Helênico",
  "Sabujo Montanhês Montenegrino",
  "Sabujo Montanhês da Baviera",
  "Sabujo Norueguês",
  "Sabujo Suíço",
  "Sabujo Sérvio",
  "Sabujo Tricolor Sérvio",
  "Sabujo da Ístria de Pelo Duro",
  "Sabujo da Ístria de Pelo Liso",
  "Sabujo de Halden",
  "Sabujo de Hamilton",
  "Sabujo de Hygen",
  "Sabujo de Posavatz",
  "Saint-Usuge Spaniel",
  "Sakhalin Husky",
  "Salish Wool Dog",
  "Saluki",
  "Samoiedo",
  "Sapsali",
  "Sarplaninac",
  "Schapendoes Holandês",
  "Schillerstövare",
  "Schipperke",
  "Schnauzer",
  "Schnauzer Gigante",
  "Schnauzer Miniatura",
  "Schnauzer Standard",
  "Schnoodle",
  "Schweizer Laufhund",
  "Schweizerischer Niederlaufhund",
  "Scotch Collie",
  "Sealyham Terrier",
  "Segugio Italiano de Pelo Curto",
  "Segugio Italiano de Pelo Áspero",
  "Segugio Maremmano",
  "Seppala Siberian Sleddog",
  "Seskar Seal Dog",
  "Setter Gordon",
  "Setter Inglês",
  "Setter Irlandês",
  "Setter Irlandês Ruivo e Branco",
  "Shar Pei",
  "Shar-Pei Chinês",
  "Sheprador Alemão",
  "Shepsky",
  "Shetland",
  "Shiba",
  "Shichon",
  "Shih-Poo",
  "Shikoku",
  "Shiranian",
  "Shorkie",
  "Silken Windhound",
  "Silky Terrier Australiano",
  "Sinhala Hound",
  "Skye Terrier",
  "Sloughi",
  "Smoushond Holandês",
  "Smålandsstövare",
  "Snauzer de Pelo Duro",
  "Soft-coated Wheaten Terrier",
  "Southern Hound",
  "Spaniel Alemão",
  "Spaniel Alpino",
  "Spaniel Anão Continental",
  "Spaniel Azul da Picardia",
  "Spaniel Francês",
  "Spaniel Inglês Anão",
  "Spaniel Japonês",
  "Spaniel Perdigueiro de Drente",
  "Spaniel Russo",
  "Spaniel Tibetano",
  "Spaniel d'Água Inglês",
  "Spaniel d'Água Irlandês",
  "Spaniel da Picardia",
  "Spaniel de Pont-Audemer",
  "Spinone Italiano",
  "Spitz Alemão",
  "Spitz Finlandês",
  "Spitz Indiano",
  "Spitz Japonês",
  "Spitz de Norboten",
  "Springer Spaniel Inglês",
  "Springer Spaniel de Gales",
  "Stabijhoun",
  "Staffordshire Bull Terrier",
  "Staghound Americano",
  "Stephens Cur",
  "Sussex Spaniel",
  "São-berdoodle",
  "São-bernardo",
  "Taco Terrier",
  "Tahltan Bear Dog",
  "Taigan",
  "Tamaskan",
  "Taylor's Bulldane",
  "Tazi",
  "Teddy Roosevelt Terrier",
  "Telomian",
  "Tenterfield Terrier",
  "Terra-nova",
  "Terri-Poo",
  "Terrier Alemão de Caça",
  "Terrier Americano Sem Pelo",
  "Terrier Australiano",
  "Terrier Branco Inglês",
  "Terrier Brasileiro",
  "Terrier Dandie Dinmont",
  "Terrier Escocês",
  "Terrier Inglês Miniatura (Preto e Castanho)",
  "Terrier Irlandês",
  "Terrier Irlandês do Glen do Imaal",
  "Terrier Japonês",
  "Terrier Preto da Rússia",
  "Terrier Tibetano",
  "Tesem",
  "Texas Heeler",
  "Thai Bangkaew",
  "Thai Ridgeback",
  "Tibalier",
  "Tibecot",
  "Tibepillon Terrier",
  "Tibetan Pap",
  "Tibetan Pom",
  "Tibetan Spaltese",
  "Torkie de Pelo Duro",
  "Tornjak",
  "Tornjak (Pastor da Bósnia-Herzegovina e Croácia)",
  "Tosa",
  "Toxirn",
  "Toy Trawler Spaniel",
  "Treeing Cur",
  "Treeing Tennessee Brindle",
  "Treeing Walker Coonhound",
  "Tricolor Francês",
  "Trigg Hound",
  "Tweed Water Spaniel",
  "Vallhund Sueco",
  "Vizla de Pelo Duro",
  "Volpino Italiano",
  "Walker Greyhound",
  "Wauzer",
  "Wee-Chon",
  "Weeranian",
  "Weiler Dane",
  "Weim-Pei",
  "Weimapeake",
  "Weimaraner",
  "Weimardale",
  "Weimardoodle",
  "Weimarman",
  "Weimshepherd",
  "Wel-Chon",
  "Welsh Corgi (Cardigan)",
  "Welsh Fox Terrier Miniatura",
  "Welsh Fox Terrier de Pelo Duro",
  "Welsh Fox Terrier de Pelo Liso",
  "Welsh Mini Fox Terrier",
  "Welsh Terrier",
  "Welshund",
  "Weltador",
  "Weshi",
  "West Australian Terrier",
  "West Highland Corgi",
  "West Highland Husky",
  "West Highland White Terrier",
  "West of Argyll Terrier",
  "Westeke",
  "Westie Staff",
  "Westie-Laso",
  "Westiepoo",
  "Westillon",
  "Westimo",
  "Weston",
  "Wetterhoun",
  "Wheagle",
  "Wheatador",
  "Wheaten Eskimo",
  "Wheaten Pei",
  "Whipador",
  "Whipperman",
  "Whippet",
  "Whippig",
  "Whoodle",
  "Wire-Poo",
  "Wirelsh Terrier",
  "Wolfhound Dane",
  "Wolfhound Irlandês",
  "Woodle",
  "Worgi",
  "Wowauzer",
  "Xiasi Dog",
  "Xoloitzcuintle",
  "Yoranian",
  "Yorkeltie",
  "Yorkie Beagle",
  "Yorkie Pin",
  "Yorkie Russell",
  "Yorkie-Apso",
  "Yorkie-ton",
  "Yorkillon",
  "Yorkinês",
  "Yorkipoo",
  "Yorksky",
  "Yorktês",
  "Yorwich",
  "Zuchon",
];

